
export const departments = {
    1: "l'Ain",
    2: "l'Aisne",
    3: "l'Allier",
    4: "les Alpes",
    5: "les Hautes-Alpes",
    6: "les Alpes-Maritimes",
    7: "l'Ardêche",
    8: "les Ardennes",
    9: "l'Ariège",
    10: "l'Aube",
    11: "l'Aude",
    12: "l'Aveyron",
    13: "les Bouches-du-Rhône",
    14: "le Calvados",
    15: "le Cantal",
    16: "la Charente",
    17: "la Charente-Maritime",
    18: "le Cher",
    19: "la Corrèze",
    20: "la Corse-du-Sud (2A) + la Haute-Corse (2B)",
    21: "la Côte-d'Or",
    22: "les Côtes d'Armor",
    23: "la Creuse",
    24: "la Dordogne",
    25: "le Doubs",
    26: "la Drôme",
    27: "l'Eure",
    28: "l'Eure-et-Loir",
    29: "le Finistère",
    30: "le Gard",
    31: "la Haute-Garonne",
    32: "le Gers",
    33: "la Gironde",
    34: "l'Hérault",
    35: "l'Île-et-Vilaine",
    36: "l'Indre",
    37: "l'Indre-et-Loire",
    38: "l'Isère",
    39: "le Jura",
    40: "les Landes",
    41: "le Loir-et-Cher",
    42: "la Loire",
    43: "la Haute-Loire",
    44: "la Loire-Atlantique",
    45: "le Loiret",
    46: "le Lot",
    47: "le Lot-et-Garonne",
    48: "la Lozère",
    49: "le Maine-et-Loire",
    50: "la Manche",
    51: "la Marne",
    52: "la Haute-Marne",
    53: "la Mayenne",
    54: "la Meurthe-et-Moselle",
    55: "la Meuse",
    56: "le Morbihan",
    57: "la Moselle",
    58: "la Nièvre",
    59: "le Nord",
    60: "l'Oise",
    61: "l'Orne",
    62: "le Pas-de-Calais",
    63: "le Puy-de-Dôme",
    64: "les Pyrénées-Atlantiques",
    65: "les Hautes-Pyrénées",
    66: "les Pyrénées-Orientales",
    67: "le Bas-Rhin",
    68: "le Haut-Rhin",
    69: "le Rhône",
    70: "la Haute-Saône",
    71: "la Saône-et-Loire",
    72: "la Sarthe",
    73: "la Savoie",
    74: "la Haute-Savoie",
    75: "Paris",
    76: "la Seine-Maritime",
    77: "la Seine-et-Marne",
    78: "les Yvelines",
    79: "les Deux-Sèvres",
    80: "la Somme",
    81: "le Tarn",
    82: "le Tarn-et-Garonne",
    83: "le Var",
    84: "le Vaucluse",
    85: "la Vendée",
    86: "la Vienne",
    87: "la Haute-Vienne",
    88: "les Vosges",
    89: "l'Yonne",
    90: "le Territoire de Belfort",
    91: "l'Essonne",
    92: "les Hauts-de-Seine",
    93: "la Seine-Saint-Denis",
    94: "le Val-de-Marne",
    95: "le Val-d'Oise",
  };

  export const ultramarins = {
    971: "la Guadeloupe",
    972: "la Martinique",
    973: "la Guyane",
    974: "La Réunion",
    975: "Saint-Pierre-et-Miquelon",
    976: "Mayotte",
    977: "Saint-Barthélemy",
    978: "Saint-Martin",
    986: "Wallis-et-Futuna",
    987: "la Polynésie française",
    988: "la Nouvelle-Calédonie",
    984: "les Terres australes et antarctiques françaises",
    989: "Clipperton",
  };

  export const oldestMan = {
    firstName: "Jiroemon",
    lastName: "Kimura",
    age: "116",
    url: "https://en.wikipedia.org/wiki/Jiroemon_Kimura",
  };
  
  export const oldestWoman = {
    firstName: "Jeanne",
    lastName: "Calment",
    age: "122",
    url: "https://en.wikipedia.org/wiki/Jeanne_Calment",
  };